spring.application.name=library

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/library
spring.datasource.username=postgres
spring.datasource.password=Alinogy7
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=greysonshawa281@gmail.com
spring.mail.password=YOUR_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Razorpay (if still used)
razorpay.key.id=rzp_test_6Xh9yZabc123
razorpay.key.secret=8dfh83hf83hfsdfh83hf
razorpay.callback.base-url=http://localhost:8080

